### ISSUE TITLE
$filePath expects path including DOCUMENT_ROOT

### ISSUE THREAD

**Issue by bosbode** [gebeer/grav-plugin-twig-getfilecontents#1]
$filePath expects path including DOCUMENT_ROOT. So this {{ getfilecontents(page.media.files['logo.svg'].url) }} won't work. Is there a way to get this working?

**Comment by gebeer** [comment]
You need to use filepath instead of url to get the full path on the server:
```
{{ getfilecontents(page.media.files['logo.svg'].filepath }}
```
See also last line in README.md ;-)
